#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "rmfakecloud"
name = "rmfakecloud"
description.en = "Host your own cloud for the remarkable"

version = "0.0.31~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://ddvk.github.io/rmfakecloud/"
userdoc = "https://ddvk.github.io/rmfakecloud/remarkable/setup/"
code = "https://github.com/ddvk/rmfakecloud"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/ddvk/rmfakecloud/releases/download/v0.0.31/rmfakecloud-x64"
    amd64.sha256 = "322baa19f1f1a66fb98e6cd349117ce3e6ece130a697a15a844d2dba6e277c1d"
    
    arm64.url = "https://github.com/ddvk/rmfakecloud/releases/download/v0.0.31/rmfakecloud-arm64"
    arm64.sha256 = "6f0ce02142a7dfa20de7377f3b4136b38d1b7acfa8a454dfb28f6c1502481cae"

    armhf.url = "https://github.com/ddvk/rmfakecloud/releases/download/v0.0.31/rmfakecloud-armv7"
    armhf.sha256 = "c491aa26c04003b71c0876036941131f4613a5b2addb24530bb7f772c8c187e6"
    
    in_subdir = false
    rename = "rmfakecloud"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "rmfakecloud-x64"
    autoupdate.asset.arm64 = "rmfakecloud-arm64"
    autoupdate.asset.armhf = "rmfakecloud-armv7"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]



